### ISSUE TITLE
User Cannot Delete Rows

### ISSUE THREAD

**Issue by awalias** [supabase/grid#35] opened 2021-06-03 07:29 UTC
![image](https://user-images.githubusercontent.com/458736/120605332-83bd2080-c480-11eb-8bed-64889894e6de.png)

https://twitter.com/brusen__/status/1400353187438075909

**Comment by phamhieu** [comment] 2021-06-03 07:48
There should be network error on delete request.

@ant can you message customer to get the error log? Thanks

**Comment by phamhieu** [comment] 2021-06-03 23:11
another user with the same issue

> When I try to delete rows, it shows they are deleted, but after a refresh they show back up.
dccabs@gmail.com
/project/tlcjcrceoownhmupvvtk/editor/table

**Comment by dccabs** [comment] 2021-06-03 23:45
Attached a video.


https://user-images.githubusercontent.com/558687/120725489-b3c5ed00-c49b-11eb-8323-fd3b23596683.mov

**Comment by phamhieu** [comment] 2021-06-04 00:19
Thanks for the video @dccabs. I can see that no delete request is sent. May I check if your table has a primary key?

Right now the logic for delete/update row data is depended on primary key [here](https://github.com/supabase/grid/blob/develop/src/services/RowService.ts#L129)

**Comment by dccabs** [comment] 2021-06-04 00:26
yeah i think that's my problem.  However,  when i created the table, i tried to make email the primary key, but after it was created it didn't have the green key next to it.

**Comment by phamhieu** [comment] 2021-06-04 00:30
> yeah i think that's my problem. However, when i created the table, i tried to make email the primary key, but after it was created it didn't have the green key next to it.

If you can try again and let use know some reproduction steps, that will be very helpful. Thank you

**Comment by dccabs** [comment] 2021-06-04 00:31
Ok I created a new test table, tried to set the primary key as the id column.  same issue when i delete and refresh.

https://user-images.githubusercontent.com/558687/120728321-436e9a00-c4a2-11eb-9897-f5e958bc8840.mov

I'm sure i'm probably doing something wrong since i'm very new to this. thanks for the help.

**Comment by phamhieu** [comment] 2021-06-04 00:55
Thanks @dccabs, it's very helpful. I can confirm that creating table with existing content causes the primary key not setup properly.

We will work on it and update you after resolving the problem.

**Comment by dccabs** [comment] 2021-06-04 01:01
thanks!

**Comment by phamhieu** [comment] 2021-06-09 09:29
@dccabs, we fixed the dashboard app. table creation with data should work properly now.

**Closed by phamhieu** 2021-06-09 09:29 UTC
Labels: bug

**Comment by dccabs** [comment] 2021-06-09 12:21
nice work, thanks
